### ISSUE TITLE
Installation error in stormpy

### ISSUE THREAD

**Issue by LebronX** [stormchecker/stormpy#41] opened 2021-08-16 20:16 UTC
Hi,

I am installing stormpy and following this link https://moves-rwth.github.io/stormpy/installation.html#compatibility-stormpy-storm. 
I clone 1.6.0 branch of stormpy and use 1.6.3 of storm. I have checked storm and it can normally run.
However, when I run `pip3 install -ve .`. It reported the following error:

```
CMake Error in CMakeLists.txt:
  Imported target "storm" includes non-existent path

    "/tmp/stormchecker-20210816-74648-1a8xb26/storm-1.6.3/resources/3rdparty/l3pp/"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in CMakeLists.txt:
  Imported target "storm" includes non-existent path

    "/tmp/stormchecker-20210816-74648-1a8xb26/storm-1.6.3/resources/3rdparty/l3pp/"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in CMakeLists.txt:
  Imported target "storm" includes non-existent path

    "/tmp/stormchecker-20210816-74648-1a8xb26/storm-1.6.3/resources/3rdparty/l3pp/"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in CMakeLists.txt:
  Imported target "storm" includes non-existent path

    "/tmp/stormchecker-20210816-74648-1a8xb26/storm-1.6.3/resources/3rdparty/l3pp/"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in CMakeLists.txt:
  Imported target "storm" includes non-existent path

    "/tmp/stormchecker-20210816-74648-1a8xb26/storm-1.6.3/resources/3rdparty/l3pp/"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in CMakeLists.txt:
  Imported target "storm" includes non-existent path

    "/tmp/stormchecker-20210816-74648-1a8xb26/storm-1.6.3/resources/3rdparty/l3pp/"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in CMakeLists.txt:
  Imported target "storm" includes non-existent path

    "/tmp/stormchecker-20210816-74648-1a8xb26/storm-1.6.3/resources/3rdparty/l3pp/"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in CMakeLists.txt:
  Imported target "storm" includes non-existent path

    "/tmp/stormchecker-20210816-74648-1a8xb26/storm-1.6.3/resources/3rdparty/l3pp/"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in CMakeLists.txt:
  Imported target "storm" includes non-existent path

    "/tmp/stormchecker-20210816-74648-1a8xb26/storm-1.6.3/resources/3rdparty/l3pp/"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in CMakeLists.txt:
  Imported target "storm" includes non-existent path

    "/tmp/stormchecker-20210816-74648-1a8xb26/storm-1.6.3/resources/3rdparty/l3pp/"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in CMakeLists.txt:
  Imported target "storm" includes non-existent path

    "/tmp/stormchecker-20210816-74648-1a8xb26/storm-1.6.3/resources/3rdparty/l3pp/"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in CMakeLists.txt:
  Imported target "storm" includes non-existent path

    "/tmp/stormchecker-20210816-74648-1a8xb26/storm-1.6.3/resources/3rdparty/l3pp/"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in CMakeLists.txt:
  Imported target "storm" includes non-existent path

    "/tmp/stormchecker-20210816-74648-1a8xb26/storm-1.6.3/resources/3rdparty/l3pp/"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in CMakeLists.txt:
  Imported target "storm" includes non-existent path

    "/tmp/stormchecker-20210816-74648-1a8xb26/storm-1.6.3/resources/3rdparty/l3pp/"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in CMakeLists.txt:
  Imported target "storm" includes non-existent path

    "/tmp/stormchecker-20210816-74648-1a8xb26/storm-1.6.3/resources/3rdparty/l3pp/"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in CMakeLists.txt:
  Imported target "storm" includes non-existent path

    "/tmp/stormchecker-20210816-74648-1a8xb26/storm-1.6.3/resources/3rdparty/l3pp/"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in CMakeLists.txt:
  Imported target "storm" includes non-existent path

    "/tmp/stormchecker-20210816-74648-1a8xb26/storm-1.6.3/resources/3rdparty/l3pp/"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in CMakeLists.txt:
  Imported target "storm" includes non-existent path

    "/tmp/stormchecker-20210816-74648-1a8xb26/storm-1.6.3/resources/3rdparty/l3pp/"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

Thanks

**Comment by tquatmann** [comment] 2021-08-17 04:56
This is a duplicate of issue #12 . In a nutshell, you probably have to build Storm [from source](https://www.stormchecker.org/documentation/obtain-storm/build.html) and not via homebrew.
We're sorry for that inconvenience. I'll update the website probably later today to make people aware of this issue.

Also, you will need Stormpy `1.6.3` if you are using Storm `1.6.3`.

**Comment by LebronX** [comment] 2021-08-20 13:10
Hi,

I installed storm from source and try to install stormpy again. However, it reports another error:

```
In file included from /usr/local/bin/storm/stormpy/src/common.h:5,
                 from /usr/local/bin/storm/stormpy/src/dft/common.h:1,
                 from /usr/local/bin/storm/stormpy/src/dft/analysis.h:3,
                 from /usr/local/bin/storm/stormpy/src/dft/analysis.cpp:1:
/usr/local/bin/storm/stormpy/resources/pybind11/include/pybind11/pybind11.h: In instantiation of ‘void pybind11::cpp_function::initialize(Func&&, Return (*)(Args ...), const Extra& ...) [with Func = storm::utility::RelevantEvents (*&)(const storm::storage::DFT<double>&, const std::vector<std::shared_ptr<const storm::logic::Formula> >&, const std::vector<std::__cxx11::basic_string<char> >&, bool); Return = storm::utility::RelevantEvents; Args = {const storm::storage::DFT<double>&, const std::vector<std::shared_ptr<const storm::logic::Formula>, std::allocator<std::shared_ptr<const storm::logic::Formula> > >&, const std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, bool}; Extra = {pybind11::name, pybind11::scope, pybind11::sibling, char [73], pybind11::arg, pybind11::arg, pybind11::arg_v}]’:
/usr/local/bin/storm/stormpy/resources/pybind11/include/pybind11/pybind11.h:53:9:   required from ‘pybind11::cpp_function::cpp_function(Return (*)(Args ...), const Extra& ...) [with Return = storm::utility::RelevantEvents; Args = {const storm::storage::DFT<double>&, const std::vector<std::shared_ptr<const storm::logic::Formula>, std::allocator<std::shared_ptr<const storm::logic::Formula> > >&, const std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, bool}; Extra = {pybind11::name, pybind11::scope, pybind11::sibling, char [73], pybind11::arg, pybind11::arg, pybind11::arg_v}]’
/usr/local/bin/storm/stormpy/resources/pybind11/include/pybind11/pybind11.h:751:22:   required from ‘pybind11::module& pybind11::module::def(const char*, Func&&, const Extra& ...) [with Func = storm::utility::RelevantEvents (*)(const storm::storage::DFT<double>&, const std::vector<std::shared_ptr<const storm::logic::Formula> >&, const std::vector<std::__cxx11::basic_string<char> >&, bool); Extra = {char [73], pybind11::arg, pybind11::arg, pybind11::arg_v}]’
/usr/local/bin/storm/stormpy/src/dft/analysis.cpp:38:262:   required from here
/usr/local/bin/storm/stormpy/resources/pybind11/include/pybind11/pybind11.h:127:58: error: static assertion failed: The number of argument annotations does not match the number of function arguments
         static_assert(detail::expected_num_args<Extra...>(sizeof...(Args), cast_in::has_args, cast_in::has_kwargs),
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[3]: *** [CMakeFiles/dft.dir/build.make:95: CMakeFiles/dft.dir/src/dft/analysis.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:185: CMakeFiles/dft.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:192: CMakeFiles/dft.dir/rule] Error 2
make: *** [Makefile:163: dft] Error 2
Traceback (most recent call last):
  File "setup.py", line 283, in <module>
    python_requires='>=3',
  File "/usr/local/bin/storm/env/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/bin/storm/env/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/usr/local/bin/storm/env/lib/python3.7/site-packages/setuptools/command/develop.py", line 136, in install_for_development
    self.run_command('build_ext')
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 195, in run
    self.build_extension(ext, cmake_args, build_args)
  File "setup.py", line 234, in build_extension
    subprocess.check_call(['cmake', '--build', '.', '--target', ext.name] + build_args, cwd=self.build_temp)
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'dft', '--config', 'Release', '--', '-j6']' returned non-zero exit status 2.
```

Thanks

**Comment by volkm** [comment] 2021-08-23 20:04
There was a compilation issue and stormpy should compile again.
However, you have a different issue which I did not encounter. Can you tell me the Storm and stormpy version you are using? Note that they both have to be compatible.

**Comment by LebronX** [comment] 2021-08-25 13:59
Hi,

I suspect that the problem is caused by the macos big sur so I change to a linux machine.

I have storm with version 1.6.3 installed and stormpy should be version 1.6.3 as well, however, it report error about `KeyError: 'carl_dir'`. Am I supposed to link with carl in stormpy installation?

Storm version:
```
Storm 1.6.3 (dev)

Date: Wed Aug 25 15:51:27 2021
Command line arguments: --version
Current working directory: /usr/local/bin/storm/storm

Version 1.6.3 (dev) (+ 101 commits) build from revision c12c0352f7f386ff45650f852bff0d6e48206ba8 (clean)
Compiled on Linux 5.4.104.1.amd64-smp using gcc (ccache) 8.3.0 with flags ' -std=c++14 -O3 -DNDEBUG -fprefetch-loop-arrays -flto -flto-partition=none -march=native -fomit-frame-pointer'
Linked with GNU Linear Programming Kit v4.65.
Linked with Microsoft Z3 Optimizer v4.4 Build 1 Rev 0.
Linked with CArL.
```

Stormpy error:
```
Installed /usr/local/bin/storm/stormpy/lib
Processing dependencies for stormpy==1.6.3
Searching for pycarl>=2.0.4
Reading https://pypi.org/simple/pycarl/
Downloading https://files.pythonhosted.org/packages/33/28/9212329aff1739ea16c4ef6266f250524e4d25dd156e09ae1e73dd5dae1c/pycarl-2.0.4.tar.gz#sha256=1e4728d51372ac12e22e19cd0c533885a5adf12e351f36355c1b73355f3ffde7
Best match: pycarl 2.0.4
Processing pycarl-2.0.4.tar.gz
Writing /tmp/easy_install-kbrb8hk8/pycarl-2.0.4/setup.cfg
Running pycarl-2.0.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-kbrb8hk8/pycarl-2.0.4/egg-dist-tmp-9k_o63xc
/usr/local/lib/python3.7/dist-packages/setuptools/dist.py:481: UserWarning: The version specified ('unknown') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % version
Traceback (most recent call last):
  File "/usr/lib/python3.7/configparser.py", line 788, in get
    value = d[option]
  File "/usr/lib/python3.7/collections/__init__.py", line 914, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.7/collections/__init__.py", line 906, in __missing__
    raise KeyError(key)
KeyError: 'carl_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/setuptools/sandbox.py", line 152, in save_modules
    yield saved
  File "/usr/local/lib/python3.7/dist-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/usr/local/lib/python3.7/dist-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/usr/local/lib/python3.7/dist-packages/setuptools/sandbox.py", line 43, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-kbrb8hk8/pycarl-2.0.4/setup.py", line 225, in <module>
    build_args = general_build_args
  File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/dist-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/local/lib/python3.7/dist-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/dist-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/usr/lib/python3.7/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/tmp/easy_install-kbrb8hk8/pycarl-2.0.4/setup.py", line 64, in run
    storm_dir = os.path.expanduser(self.config.get_as_string("storm_dir"))
  File "/usr/local/bin/storm/stormpy/setup/config.py", line 81, in get_as_string
    return self.config.get("build_ext", name)
  File "/usr/lib/python3.7/configparser.py", line 791, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'carl_dir' in section: 'build_ext'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 283, in <module>
    python_requires='>=3',
  File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/dist-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/usr/local/lib/python3.7/dist-packages/setuptools/command/develop.py", line 151, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/usr/local/lib/python3.7/dist-packages/setuptools/command/easy_install.py", line 745, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 768, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 1051, in best_match
    return self.obtain(req, installer)
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 1063, in obtain
    return installer(requirement)
  File "/usr/local/lib/python3.7/dist-packages/setuptools/command/easy_install.py", line 669, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/local/lib/python3.7/dist-packages/setuptools/command/easy_install.py", line 695, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/local/lib/python3.7/dist-packages/setuptools/command/easy_install.py", line 890, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/local/lib/python3.7/dist-packages/setuptools/command/easy_install.py", line 1162, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/local/lib/python3.7/dist-packages/setuptools/command/easy_install.py", line 1146, in run_setup
    run_setup(setup_script, args)
  File "/usr/local/lib/python3.7/dist-packages/setuptools/sandbox.py", line 257, in run_setup
    raise
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.7/dist-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.7/dist-packages/setuptools/sandbox.py", line 164, in save_modules
    saved_exc.resume()
  File "/usr/local/lib/python3.7/dist-packages/setuptools/sandbox.py", line 139, in resume
    raise exc.with_traceback(self._tb)
  File "/usr/local/lib/python3.7/dist-packages/setuptools/sandbox.py", line 152, in save_modules
    yield saved
  File "/usr/local/lib/python3.7/dist-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/usr/local/lib/python3.7/dist-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/usr/local/lib/python3.7/dist-packages/setuptools/sandbox.py", line 43, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-kbrb8hk8/pycarl-2.0.4/setup.py", line 225, in <module>
    build_args = general_build_args
  File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/dist-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/local/lib/python3.7/dist-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/dist-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/usr/lib/python3.7/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/tmp/easy_install-kbrb8hk8/pycarl-2.0.4/setup.py", line 64, in run
    storm_dir = os.path.expanduser(self.config.get_as_string("storm_dir"))
  File "/usr/local/bin/storm/stormpy/setup/config.py", line 81, in get_as_string
    return self.config.get("build_ext", name)
  File "/usr/lib/python3.7/configparser.py", line 791, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'carl_dir' in section: 'build_ext'
```

**Comment by oyendrila-dobe** [comment] 2021-11-05 15:11
I'm trying to install stormpy 1.6.3 with storm 1.6.3 and I'm still facing this error. I do have pycarl successfully installed in my system which is globally available. Is there a way to force stormpy to use that instead of downloading (as in 5th line of the stormpy error screenshot above)?

**Comment by volkm** [comment] 2021-11-08 09:43
Manually installing pycarl is the best approach right now. In that case, stormpy should automatically detect the installed version of pycarl and not install it from pypi.

Are you using a virtual environment? Maybe pycarl is not installed in this environment. You can check with `pip list`. This should give you the list of packages which are installed in your current environment.

**Comment by oyendrila-dobe** [comment] 2021-11-08 16:17
I have pycarl 2.0.4 installed, which shows in the ```pip list```. Somehow stormpy cannot find it and it downloading it for installation and encountering this error. I'm trying to figure out which line in setup.py is calling pycarl and not getting an expected return hence starting the download. I have attached the error log for your help.
[error_stormpy_installation.txt](https://github.com/moves-rwth/stormpy/files/7498442/error_stormpy_installation.txt)

**Comment by oyendrila-dobe** [comment] 2021-11-23 22:31
Was there any resolution to this issue?

**Comment by volkm** [comment] 2021-11-25 15:42
Thanks for the reminder.

I still do not know where the problem comes from. Checking the dependencies should be done by pip itself and if pycarl is installed, it should be found during the process.
My suggestion is to try the following workaround for now:
remove [this line](https://github.com/moves-rwth/stormpy/blob/master/setup.py#L276) in `setup.py` which defines pycarl as a dependency. Afterwards it should not be automatically installed anymore and the rest hopefully works as expected.

One last remark: be aware that stormpy printed a warning about using a different Storm version:
`Stormpy - Warning: Using different storm directory ~/Documents/setpro/storm/build instead of given ~/Documents/Research/setup/storm/build/bin`

**Comment by oyendrila-dobe** [comment] 2021-11-30 19:01
You were absolutely right. Commenting the line in setup and forcing the storm directory did the trick. The installation ran smoothly. Thank you!

**Closed as completed** 2022-03-16 09:06 UTC
